# Sensor Thresholds and Ranges

# Pressure (psi)
PRESSURE_LOW_THRESHOLD = 55
PRESSURE_NORMAL_MIN = 60
PRESSURE_NORMAL_MAX = 70
PRESSURE_LEAK_MIN = 40
PRESSURE_LEAK_MAX = 50

# Acoustic (dB)
ACOUSTIC_HIGH_THRESHOLD = 5
ACOUSTIC_NORMAL_MIN = 2.0
ACOUSTIC_NORMAL_MAX = 3.5
ACOUSTIC_LEAK_MIN = 6.0
ACOUSTIC_LEAK_MAX = 8.0

# Flow (L/s)
FLOW_HIGH_THRESHOLD = 110
FLOW_NORMAL_MIN = 80
FLOW_NORMAL_MAX = 100
FLOW_LEAK_MIN = 120
FLOW_LEAK_MAX = 140
